name: Push

on:
  push:

jobs:
  dump_contexts_to_log:
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ stable ]
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: make

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: git log
        run: git log --graph --pretty=tformat:'%Cred%h%Creset %Cblue%G?%Creset -%C(auto)%d%Creset %s %Cgreen(%an %ar)%Creset' --branches --remotes

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3ab19875d7f33278aa6f7cdbdd1f37ed29bbace2
        with:
          version: v1.57
          # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0
          # install-mode: "goinstall"
          only-new-issues: true
